{
	"id": "CVE-2025-24126",
	"sourceIdentifier": "product-security@apple.com",
	"vulnStatus": "Awaiting Analysis",
	"published": "2025-01-27T22:15:17.603",
	"lastModified": "2025-01-28T15:15:13.743",
	"descriptions": [
		{
			"lang": "en",
			"value": "An input validation issue was addressed. This issue is fixed in visionOS 2.3, iOS 18.3 and iPadOS 18.3, macOS Sequoia 15.3, watchOS 11.3, tvOS 18.3. An attacker on the local network may be able to cause unexpected system termination or corrupt process memory."
		},
		{
			"lang": "es",
			"value": "Se solucionó un problema de validación de entrada. Este problema se solucionó en visionOS 2.3, iOS 18.3 y iPadOS 18.3, macOS Sequoia 15.3, watchOS 11.3 y tvOS 18.3. Un atacante en la red local podría provocar la finalización inesperada de sistema o dañar la memoria del proceso."
		}
	],
	"references": [
		{
			"source": "product-security@apple.com",
			"url": "https://support.apple.com/en-us/122066"
		},
		{
			"source": "product-security@apple.com",
			"url": "https://support.apple.com/en-us/122068"
		},
		{
			"source": "product-security@apple.com",
			"url": "https://support.apple.com/en-us/122071"
		},
		{
			"source": "product-security@apple.com",
			"url": "https://support.apple.com/en-us/122072"
		},
		{
			"source": "product-security@apple.com",
			"url": "https://support.apple.com/en-us/122073"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "NONE",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "HIGH",
					"integrityImpact": "HIGH",
					"availabilityImpact": "HIGH",
					"baseScore": 9.8,
					"baseSeverity": "CRITICAL"
				},
				"exploitabilityScore": 3.9,
				"impactScore": 5.9
			}
		]
	}
}
