{
	"id": "CVE-2023-28455",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Awaiting Analysis",
	"published": "2024-09-18T15:15:14.020",
	"lastModified": "2024-09-20T12:30:17.483",
	"descriptions": [
		{
			"lang": "en",
			"value": "An issue was discovered in Technitium through 11.0.2. The forwarding mode enables attackers to create a query loop using Technitium resolvers, launching amplification attacks and causing potential DoS."
		},
		{
			"lang": "es",
			"value": "Se descubrió un problema en Technitium hasta la versión 11.0.2. El modo de reenvío permite a los atacantes crear un bucle de consultas mediante los solucionadores de Technitium, lanzando ataques de amplificación y provocando posibles ataques de denegación de servicio (DoS)."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://gist.github.com/idealeer/89947ca07836fd0f7e9761198ca9a0f3"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://technitium.com/dns/"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "NONE",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "HIGH",
					"baseScore": 7.5,
					"baseSeverity": "HIGH"
				},
				"exploitabilityScore": 3.9,
				"impactScore": 3.6
			}
		]
	},
	"weaknesses": [
		{
			"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-406"
				}
			]
		}
	]
}
