{
	"id": "CVE-2023-5870",
	"sourceIdentifier": "secalert@redhat.com",
	"vulnStatus": "Awaiting Analysis",
	"published": "2023-12-10T18:15:07.643",
	"lastModified": "2023-12-11T16:15:42.990",
	"descriptions": [
		{
			"lang": "en",
			"value": "A flaw was found in PostgreSQL involving the pg_cancel_backend role that signals background workers, including the logical replication launcher, autovacuum workers, and the autovacuum launcher. Successful exploitation requires a non-core extension with a less-resilient background worker and would affect that specific background worker only. This issue may allow a remote high privileged user to launch a denial of service (DoS) attack."
		},
		{
			"lang": "es",
			"value": "Se encontró una falla en PostgreSQL que involucra la función pg_cancel_backend que señala a los trabajadores en segundo plano, incluido el iniciador de replicación lógica, los trabajadores de autovacuum y el iniciador de autovacuum. La explotación exitosa requiere una extensión no central con un trabajador en segundo plano menos resistente y afectaría únicamente a ese trabajador en segundo plano específico. Este problema puede permitir que un usuario remoto con privilegios elevados lance un ataque de denegación de servicio (DoS)."
		}
	],
	"references": [
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7545"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7579"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7580"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7581"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7616"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7656"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7666"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7667"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7694"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7695"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/errata/RHSA-2023:7714"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/security/cve/CVE-2023-5870"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2247170"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://www.postgresql.org/about/news/postgresql-161-155-1410-1313-1217-and-1122-released-2749/"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://www.postgresql.org/support/security/CVE-2023-5870/"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "secalert@redhat.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:N/I:N/A:L",
					"attackVector": "NETWORK",
					"attackComplexity": "HIGH",
					"privilegesRequired": "HIGH",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "LOW",
					"baseScore": 2.2,
					"baseSeverity": "LOW"
				},
				"exploitabilityScore": 0.7,
				"impactScore": 1.4
			}
		]
	},
	"weaknesses": [
		{
			"source": "secalert@redhat.com",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-400"
				}
			]
		}
	]
}
