{
	"id": "CVE-2023-46960",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Received",
	"published": "2024-04-29T21:15:47.527",
	"lastModified": "2024-04-29T21:15:47.527",
	"descriptions": [
		{
			"lang": "en",
			"value": "Buffer Overflow vulnerability in PyPXE v.1.8.4 allows a remote attacker to cause a denial of service via the handle function in the tftp module."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://github.com/pypxe/PyPXE/issues/206"
		}
	],
	"metrics": {}
}
