{
	"id": "CVE-2023-6560",
	"sourceIdentifier": "secalert@redhat.com",
	"vulnStatus": "Awaiting Analysis",
	"published": "2023-12-09T00:15:07.877",
	"lastModified": "2023-12-10T11:51:04.043",
	"descriptions": [
		{
			"lang": "en",
			"value": "An out-of-bounds memory access flaw was found in the io_uring SQ/CQ rings functionality in the Linux kernel. This issue could allow a local user to crash the system."
		},
		{
			"lang": "es",
			"value": "Se encontró una falla de acceso a memoria fuera de los límites en la funcionalidad de anillos io_uring SQ/CQ en el kernel de Linux. Este problema podría permitir que un usuario local bloquee el sistema."
		}
	],
	"references": [
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/security/cve/CVE-2023-6560"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2253249"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://patchwork.kernel.org/project/io-uring/patch/20231130194633.649319-2-axboe@kernel.dk/"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "secalert@redhat.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
					"attackVector": "LOCAL",
					"attackComplexity": "LOW",
					"privilegesRequired": "LOW",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "HIGH",
					"baseScore": 5.5,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 1.8,
				"impactScore": 3.6
			}
		]
	},
	"weaknesses": [
		{
			"source": "secalert@redhat.com",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-823"
				}
			]
		}
	]
}
