{
	"id": "CVE-2023-50308",
	"sourceIdentifier": "psirt@us.ibm.com",
	"vulnStatus": "Awaiting Analysis",
	"published": "2024-01-22T19:15:09.003",
	"lastModified": "2024-01-22T20:28:17.417",
	"descriptions": [
		{
			"lang": "en",
			"value": "IBM Db2 for Linux, UNIX and Windows (includes DB2 Connect Server) 11.5 under certain circumstances could allow an authenticated user to the database to cause a denial of service when a statement is run on columnar tables.  IBM X-Force ID:  273393."
		}
	],
	"references": [
		{
			"source": "psirt@us.ibm.com",
			"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/273393"
		},
		{
			"source": "psirt@us.ibm.com",
			"url": "https://www.ibm.com/support/pages/node/7105506"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "psirt@us.ibm.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "LOW",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "HIGH",
					"baseScore": 6.5,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 2.8,
				"impactScore": 3.6
			}
		]
	},
	"weaknesses": [
		{
			"source": "psirt@us.ibm.com",
			"type": "Primary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-20"
				}
			]
		}
	]
}
