{
	"id": "CVE-2024-3219",
	"sourceIdentifier": "cna@python.org",
	"vulnStatus": "Received",
	"published": "2024-07-29T22:15:04.970",
	"lastModified": "2024-07-30T01:15:14.217",
	"descriptions": [
		{
			"lang": "en",
			"value": "There is a MEDIUM severity vulnerability affecting CPython.\n\nThe\n “socket” module provides a pure-Python fallback to the \nsocket.socketpair() function for platforms that don’t support AF_UNIX, \nsuch as Windows. This pure-Python implementation uses AF_INET or \nAF_INET6 to create a local connected pair of sockets. The connection \nbetween the two sockets was not verified before passing the two sockets \nback to the user, which leaves the server socket vulnerable to a \nconnection race from a malicious local peer.\n\nPlatforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included."
		},
		{
			"lang": "es",
			"value": "Existe una vulnerabilidad de gravedad MEDIA que afecta a CPython. El módulo \"socket\" proporciona un respaldo de Python puro a la función socket.socketpair() para plataformas que no admiten AF_UNIX, como Windows. Esta implementación pura de Python utiliza AF_INET o AF_INET6 para crear un par de sockets conectados localmente. La conexión entre los dos sockets no se verificó antes de devolverlos al usuario, lo que deja al socket del servidor vulnerable a una ejecución de conexión de un par local malicioso. Las plataformas que admiten AF_UNIX, como Linux y macOS, no se ven afectadas por esta vulnerabilidad. Las versiones anteriores a CPython 3.5 no se ven afectadas debido a que no se incluye la API vulnerable."
		}
	],
	"references": [
		{
			"source": "cna@python.org",
			"url": "http://www.openwall.com/lists/oss-security/2024/07/29/3"
		},
		{
			"source": "cna@python.org",
			"url": "https://github.com/python/cpython/issues/122133"
		},
		{
			"source": "cna@python.org",
			"url": "https://github.com/python/cpython/pull/122134"
		},
		{
			"source": "cna@python.org",
			"url": "https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/"
		}
	],
	"metrics": {}
}
