{
	"id": "CVE-2024-23829",
	"sourceIdentifier": "security-advisories@github.com",
	"vulnStatus": "Undergoing Analysis",
	"published": "2024-01-29T23:15:08.767",
	"lastModified": "2024-02-05T02:15:47.367",
	"descriptions": [
		{
			"lang": "en",
			"value": "aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Security-sensitive parts of the Python HTTP parser retained minor differences in allowable character sets, that must trigger error handling to robustly match frame boundaries of proxies in order to protect against injection of additional requests. Additionally, validation could trigger exceptions that were not handled consistently with processing of other malformed input.  Being more lenient than internet standards require could, depending on deployment environment, assist in request smuggling. The unhandled exception could cause excessive resource consumption on the application server and/or its logging facilities. This vulnerability exists due to an incomplete fix for CVE-2023-47627. Version 3.9.2 fixes this vulnerability."
		},
		{
			"lang": "es",
			"value": "aiohttp es un framework cliente/servidor HTTP asíncrono para asyncio y Python. Las partes sensibles a la seguridad del analizador HTTP de Python conservaron diferencias menores en los conjuntos de caracteres permitidos, que deben activar el manejo de errores para hacer coincidir de manera sólida los límites de marco de los servidores proxy para proteger contra la inyección de solicitudes adicionales. Además, la validación podría desencadenar excepciones que no se manejaron de manera consistente con el procesamiento de otras entradas con formato incorrecto. Ser más indulgente de lo que exigen los estándares de Internet podría, según el entorno de implementación, ayudar en el contrabando de solicitudes. La excepción no controlada podría causar un consumo excesivo de recursos en el servidor de aplicaciones y/o sus instalaciones de registro. Esta vulnerabilidad existe debido a una solución incompleta para CVE-2023-47627. La versión 3.9.2 corrige esta vulnerabilidad."
		}
	],
	"references": [
		{
			"source": "security-advisories@github.com",
			"url": "https://github.com/aio-libs/aiohttp/commit/33ccdfb0a12690af5bb49bda2319ec0907fa7827"
		},
		{
			"source": "security-advisories@github.com",
			"url": "https://github.com/aio-libs/aiohttp/pull/8074"
		},
		{
			"source": "security-advisories@github.com",
			"url": "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-8qpw-xqxj-h4r2"
		},
		{
			"source": "security-advisories@github.com",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7/"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "security-advisories@github.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "NONE",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "LOW",
					"availabilityImpact": "LOW",
					"baseScore": 6.5,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 3.9,
				"impactScore": 2.5
			}
		]
	},
	"weaknesses": [
		{
			"source": "security-advisories@github.com",
			"type": "Primary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-444"
				}
			]
		}
	]
}
