{
	"id": "CVE-2024-27254",
	"sourceIdentifier": "psirt@us.ibm.com",
	"vulnStatus": "Awaiting Analysis",
	"published": "2024-04-03T13:16:02.220",
	"lastModified": "2024-04-03T17:24:18.150",
	"descriptions": [
		{
			"lang": "en",
			"value": "IBM Db2 for Linux, UNIX and Windows (includes DB2 Connect Server) 10.5, 11.1, and 11.5 federated server is vulnerable to denial of service with a specially crafted query under certain conditions.  IBM X-Force ID:  283813."
		}
	],
	"references": [
		{
			"source": "psirt@us.ibm.com",
			"url": "https://https://exchange.xforce.ibmcloud.com/vulnerabilities/283813"
		},
		{
			"source": "psirt@us.ibm.com",
			"url": "https://www.ibm.com/support/pages/node/7145727"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "psirt@us.ibm.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
					"attackVector": "NETWORK",
					"attackComplexity": "HIGH",
					"privilegesRequired": "LOW",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "HIGH",
					"baseScore": 5.3,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 1.6,
				"impactScore": 3.6
			}
		]
	},
	"weaknesses": [
		{
			"source": "psirt@us.ibm.com",
			"type": "Primary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-20"
				}
			]
		}
	]
}
