{
	"id": "CVE-2024-3955",
	"sourceIdentifier": "cvd@cert.pl",
	"vulnStatus": "Awaiting Analysis",
	"published": "2024-05-02T10:15:08.630",
	"lastModified": "2024-05-02T13:27:25.103",
	"descriptions": [
		{
			"lang": "en",
			"value": "URL GET parameter \"logtime\" utilized within the \"downloadlog\" function from \"cbpi/http_endpoints/http_system.py\" is subsequently passed to the \"os.system\" function in \"cbpi/controller/system_controller.py\" without prior validation allowing to execute arbitrary code.This issue affects CraftBeerPi 4: from 4.0.0.58 (commit 563fae9) before 4.4.1.a1 (commit 57572c7).\n\n"
		},
		{
			"lang": "es",
			"value": "El parámetro GET de URL \"logtime\" utilizado dentro de la función \"downloadlog\" de \"cbpi/http_endpoints/http_system.py\" se pasa posteriormente a la función \"os.system\" en \"cbpi/controller/system_controller.py\" sin validación previa que permita ejecutar código arbitrario. Este problema afecta a CraftBeerPi 4: desde 4.0.0.58 (commit 563fae9) antes de 4.4.1.a1 (commit 57572c7)."
		}
	],
	"references": [
		{
			"source": "cvd@cert.pl",
			"url": "https://cert.pl/en/posts/2024/05/CVE-2024-3955/"
		},
		{
			"source": "cvd@cert.pl",
			"url": "https://cert.pl/posts/2024/05/CVE-2024-3955/"
		},
		{
			"source": "cvd@cert.pl",
			"url": "https://github.com/PiBrewing/craftbeerpi4/issues/132"
		}
	],
	"metrics": {},
	"weaknesses": [
		{
			"source": "cvd@cert.pl",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-94"
				}
			]
		}
	]
}
