{
	"id": "CVE-2024-6237",
	"sourceIdentifier": "secalert@redhat.com",
	"vulnStatus": "Undergoing Analysis",
	"published": "2024-07-09T17:15:48.960",
	"lastModified": "2024-07-09T18:18:38.713",
	"descriptions": [
		{
			"lang": "en",
			"value": "A flaw was found in the 389 Directory Server. This flaw allows an unauthenticated user to cause a systematic server crash while sending a specific extended search request, leading to a denial of service."
		},
		{
			"lang": "es",
			"value": "Se encontró un fallo en 389 Directory Server. Este fallo permite que un usuario no autenticado provoque un fallo sistemático del servidor mientras envía una solicitud de búsqueda extendida específica, lo que lleva a una denegación de servicio."
		}
	],
	"references": [
		{
			"source": "secalert@redhat.com",
			"url": "https://access.redhat.com/security/cve/CVE-2024-6237"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2293579"
		},
		{
			"source": "secalert@redhat.com",
			"url": "https://github.com/389ds/389-ds-base/issues/5989"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "secalert@redhat.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "NONE",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "LOW",
					"baseScore": 5.3,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 3.9,
				"impactScore": 1.4
			}
		]
	},
	"weaknesses": [
		{
			"source": "secalert@redhat.com",
			"type": "Primary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-230"
				}
			]
		}
	]
}
