{
	"id": "CVE-2024-36610",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Rejected",
	"published": "2024-11-29T20:15:20.237",
	"lastModified": "2024-12-24T21:15:18.280",
	"descriptions": [
		{
			"lang": "en",
			"value": "Rejected reason: DO NOT USE THIS CANDIDATE NUMBER. Reason: This candidate was issued in error. Notes: All references and descriptions in this candidate have been removed to prevent accidental usage."
		}
	],
	"references": [],
	"metrics": {}
}
