{
	"id": "CVE-2024-45201",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Received",
	"published": "2024-08-22T20:15:10.063",
	"lastModified": "2024-08-22T20:15:10.063",
	"descriptions": [
		{
			"lang": "en",
			"value": "An issue was discovered in llama_index before 0.10.38. download/integration.py includes an exec call for import {cls_name}."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://github.com/run-llama/llama_index/compare/v0.10.37...v0.10.38"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://github.com/run-llama/llama_index/pull/13523"
		}
	],
	"metrics": {}
}
