{
  "cve": {
    "id": "CVE-2020-16149",
    "sourceIdentifier": "cve@mitre.org",
    "vulnStatus": "Rejected",
    "published": "2020-09-03T15:15:11.363",
    "lastModified": "2023-11-07T03:18:12.687",
    "descriptions": [
      {
        "lang": "en",
        "value": "Rejected reason: DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its requestor. Notes: none"
      }
    ],
    "references": [],
    "metrics": {}
  }
}
