{
  "cve": {
    "id": "CVE-2022-47515",
    "sourceIdentifier": "cve@mitre.org",
    "vulnStatus": "Analyzed",
    "published": "2022-12-18T05:15:11.100",
    "lastModified": "2022-12-22T18:16:09.110",
    "descriptions": [
      {
        "lang": "en",
        "value": "An issue was discovered in drachtio-server before 0.8.20. It allows remote attackers to cause a denial of service (daemon crash) via a long message in a TCP request that leads to std::length_error."
      }
    ],
    "references": [
      {
        "source": "cve@mitre.org",
        "tags": [
          "Patch",
          "Third Party Advisory"
        ],
        "url": "https://github.com/drachtio/drachtio-server/commit/4cf9fe2c420b86c16442215d449d40be777c1911"
      },
      {
        "source": "cve@mitre.org",
        "tags": [
          "Exploit",
          "Third Party Advisory"
        ],
        "url": "https://github.com/drachtio/drachtio-server/issues/245"
      }
    ],
    "metrics": {
      "cvssMetricV31": [
        {
          "source": "nvd@nist.gov",
          "type": "Primary",
          "cvssData": {
            "version": "3.1",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "attackVector": "NETWORK",
            "attackComplexity": "LOW",
            "privilegesRequired": "NONE",
            "userInteraction": "NONE",
            "scope": "UNCHANGED",
            "confidentialityImpact": "NONE",
            "integrityImpact": "NONE",
            "availabilityImpact": "HIGH",
            "baseScore": 7.5,
            "baseSeverity": "HIGH"
          },
          "exploitabilityScore": 3.9,
          "impactScore": 3.6
        }
      ]
    },
    "weaknesses": [
      {
        "source": "nvd@nist.gov",
        "type": "Primary",
        "description": [
          {
            "lang": "en",
            "value": "NVD-CWE-noinfo"
          }
        ]
      }
    ],
    "configurations": [
      {
        "nodes": [
          {
            "operator": "OR",
            "cpeMatch": [
              {
                "vulnerable": true,
                "criteria": "cpe:2.3:a:drachtio:drachtio-server:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "BE06DCDE-7FE0-4BAB-9130-985502E95875",
                "versionEndExcluding": "0.8.20"
              }
            ]
          }
        ]
      }
    ]
  }
}
