{
	"id": "CVE-2022-31667",
	"sourceIdentifier": "security@vmware.com",
	"vulnStatus": "Undergoing Analysis",
	"published": "2024-11-14T12:15:16.390",
	"lastModified": "2024-11-15T13:58:08.913",
	"descriptions": [
		{
			"lang": "en",
			"value": "Harbor fails to validate the user permissions when updating a robot account that belongs to a project that the authenticated user doesn’t have access to. \n\nBy sending a request that attempts to update a robot account, and specifying a robot account id and robot account name that belongs to a different project that the user doesn’t have access to, it was possible to revoke the robot account permissions."
		},
		{
			"lang": "es",
			"value": "Harbor no puede validar los permisos de usuario al actualizar una cuenta de robot que pertenece a un proyecto al que el usuario autenticado no tiene acceso. Al enviar una solicitud que intenta actualizar una cuenta de robot y especificar un ID y un nombre de cuenta de robot que pertenecen a un proyecto diferente al que el usuario no tiene acceso, fue posible revocar los permisos de la cuenta de robot."
		}
	],
	"references": [
		{
			"source": "security@vmware.com",
			"url": "https://github.com/goharbor/harbor/security/advisories/GHSA-xx9w-464f-7h6f"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "security@vmware.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:L/A:L",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "LOW",
					"userInteraction": "NONE",
					"scope": "CHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "LOW",
					"availabilityImpact": "LOW",
					"baseScore": 6.4,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 3.1,
				"impactScore": 2.7
			}
		]
	},
	"weaknesses": [
		{
			"source": "security@vmware.com",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-285"
				}
			]
		}
	]
}
