{
	"id": "CVE-2021-46179",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Analyzed",
	"published": "2023-08-22T19:16:21.883",
	"lastModified": "2023-08-25T19:52:59.843",
	"descriptions": [
		{
			"lang": "en",
			"value": "Reachable Assertion vulnerability in upx before 4.0.0 allows attackers to cause a denial of service via crafted file passed to the the readx function."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"tags": [
				"Issue Tracking",
				"Patch"
			],
			"url": "https://github.com/upx/upx/issues/545"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "nvd@nist.gov",
				"type": "Primary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "NONE",
					"userInteraction": "REQUIRED",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "HIGH",
					"baseScore": 6.5,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 2.8,
				"impactScore": 3.6
			}
		]
	},
	"weaknesses": [
		{
			"source": "nvd@nist.gov",
			"type": "Primary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-617"
				}
			]
		}
	],
	"configurations": [
		{
			"nodes": [
				{
					"operator": "OR",
					"cpeMatch": [
						{
							"vulnerable": true,
							"criteria": "cpe:2.3:a:upx_project:upx:*:*:*:*:*:*:*:*",
							"matchCriteriaId": "1E4C95CD-E2A9-47E3-9866-FD4B7ECF14AA",
							"versionEndExcluding": "4.0.0"
						}
					]
				}
			]
		}
	]
}
